package org.wiredwidgets.cow.ac.workflowsummary.ui;

import java.awt.Color;

/**
 * A simple pop-up dialog providing an explanation as to what colors represent
 * what states in the {@link ChicletTopComponent} and
 * {@link org.wiredwidgets.cow.ac.workflowviewer.WorkflowDetailsTopComponent}.
 * The states-to-color mapping is defined programatically in
 * {@link org.wiredwidgets.cow.ac.workflowsummary.model.ProcessStateByGroupAndUser},
 * but the dialog is not dynamically generated to keep things much simpler.
 *
 * @author MJRUSSELL
 * @see
 * org.wiredwidgets.cow.ac.workflowsummary.model.ProcessStateByGroupAndUser.CompletionState
 */
public class ColorLegendDialog extends javax.swing.JDialog {

    /**
     * Creates new form ColorLegendDialog
     */
    public ColorLegendDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        approvedLabel = new javax.swing.JLabel();
        rejectedLabel = new javax.swing.JLabel();
        redField = new javax.swing.JFormattedTextField();
        inProgressLabel = new javax.swing.JLabel();
        cyanField = new javax.swing.JFormattedTextField();
        greenField = new javax.swing.JFormattedTextField();
        notYetAssignedLabel = new javax.swing.JLabel();
        whiteField = new javax.swing.JFormattedTextField();
        lightGrayField = new javax.swing.JFormattedTextField();
        undeterminableLabel = new javax.swing.JLabel();
        noTaskLabel = new javax.swing.JLabel();
        blackField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        approvedLabel.setText(org.openide.util.NbBundle.getMessage(ColorLegendDialog.class, "ColorLegendDialog.approvedLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 25;
        getContentPane().add(approvedLabel, gridBagConstraints);

        rejectedLabel.setText(org.openide.util.NbBundle.getMessage(ColorLegendDialog.class, "ColorLegendDialog.rejectedLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 25;
        getContentPane().add(rejectedLabel, gridBagConstraints);

        redField.setBackground(Color.RED);
        redField.setEditable(false);
        redField.setText(org.openide.util.NbBundle.getMessage(ColorLegendDialog.class, "ColorLegendDialog.redField.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 15;
        getContentPane().add(redField, gridBagConstraints);

        inProgressLabel.setText(org.openide.util.NbBundle.getMessage(ColorLegendDialog.class, "ColorLegendDialog.inProgressLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 25;
        getContentPane().add(inProgressLabel, gridBagConstraints);

        cyanField.setBackground(Color.CYAN);
        cyanField.setEditable(false);
        cyanField.setText(org.openide.util.NbBundle.getMessage(ColorLegendDialog.class, "ColorLegendDialog.cyanField.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 15;
        getContentPane().add(cyanField, gridBagConstraints);

        greenField.setBackground(Color.GREEN);
        greenField.setEditable(false);
        greenField.setText(org.openide.util.NbBundle.getMessage(ColorLegendDialog.class, "ColorLegendDialog.greenField.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 15;
        getContentPane().add(greenField, gridBagConstraints);

        notYetAssignedLabel.setText(org.openide.util.NbBundle.getMessage(ColorLegendDialog.class, "ColorLegendDialog.notYetAssignedLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 25;
        getContentPane().add(notYetAssignedLabel, gridBagConstraints);

        whiteField.setBackground(Color.WHITE);
        whiteField.setEditable(false);
        whiteField.setText(org.openide.util.NbBundle.getMessage(ColorLegendDialog.class, "ColorLegendDialog.whiteField.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 15;
        getContentPane().add(whiteField, gridBagConstraints);

        lightGrayField.setBackground(Color.LIGHT_GRAY);
        lightGrayField.setEditable(false);
        lightGrayField.setText(org.openide.util.NbBundle.getMessage(ColorLegendDialog.class, "ColorLegendDialog.lightGrayField.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 15;
        getContentPane().add(lightGrayField, gridBagConstraints);

        undeterminableLabel.setText(org.openide.util.NbBundle.getMessage(ColorLegendDialog.class, "ColorLegendDialog.undeterminableLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 25;
        getContentPane().add(undeterminableLabel, gridBagConstraints);

        noTaskLabel.setText(org.openide.util.NbBundle.getMessage(ColorLegendDialog.class, "ColorLegendDialog.noTaskLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 25;
        getContentPane().add(noTaskLabel, gridBagConstraints);

        blackField.setBackground(Color.BLACK);
        blackField.setEditable(false);
        blackField.setText(org.openide.util.NbBundle.getMessage(ColorLegendDialog.class, "ColorLegendDialog.blackField.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 15;
        getContentPane().add(blackField, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel approvedLabel;
    private javax.swing.JFormattedTextField blackField;
    private javax.swing.JFormattedTextField cyanField;
    private javax.swing.JFormattedTextField greenField;
    private javax.swing.JLabel inProgressLabel;
    private javax.swing.JFormattedTextField lightGrayField;
    private javax.swing.JLabel noTaskLabel;
    private javax.swing.JLabel notYetAssignedLabel;
    private javax.swing.JFormattedTextField redField;
    private javax.swing.JLabel rejectedLabel;
    private javax.swing.JLabel undeterminableLabel;
    private javax.swing.JFormattedTextField whiteField;
    // End of variables declaration//GEN-END:variables
}
