// Generated by CoffeeScript 1.7.1
(function() {
  var AdminViewModel;

  $(function() {
    return ko.applyBindings(new AdminViewModel());
  });

  AdminViewModel = (function() {
    function AdminViewModel() {}

    AdminViewModel.prototype.adminFunction = function() {};

    return AdminViewModel;

  })();

}).call(this);

//# sourceMappingURL=admin.map
