// Generated by CoffeeScript 1.7.1
(function() {
  var Activities, Activity, ActivityFactory, Decision, Exit, HumanTask, Loop, Option, PrettyPrintVisitor, ScriptTask, ServiceTask, Signal, Subprocess, Workflow, WorkflowBuilderViewModel, WorkflowXmlConverter, dndOptions,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  $(function() {
    ko.applyBindings(new WorkflowBuilderViewModel());
    return $(".draggable").draggable({
      revert: true,
      cursorAt: {
        top: -5,
        left: -5
      },
      connectToFancytree: true
    });
  });

  dndOptions = {
    autoExpandMS: 100,
    preventVoidMoves: true,
    preventRecursiveMoves: true,
    dragStart: function(node) {
      return node.data.draggable;
    },
    dragEnter: function(target, data) {
      return target.data.act.dragEnter(data);
    },
    dragDrop: function(target, data) {
      if (data.hitMode === "over") {
        return data.otherNode.moveTo(target.getFirstChild(), "before");
      } else {
        return data.otherNode.moveTo(target, data.hitMode);
      }
    }
  };

  WorkflowBuilderViewModel = (function() {
    function WorkflowBuilderViewModel() {
      this.save = __bind(this.save, this);
      this.prettyPrint = __bind(this.prettyPrint, this);
      this.configTree = __bind(this.configTree, this);
      this.loadWorkflow = __bind(this.loadWorkflow, this);
      this.workflow = ko.observable();
      this.loadWorkflow("vars-test");
      this.selectedActivity = ko.observable();
      this.workflowComponents = ActivityFactory.all();
    }

    WorkflowBuilderViewModel.prototype.loadWorkflow = function(workflowName) {
      return COW.cowRequest("processes/" + workflowName).done((function(_this) {
        return function(data) {
          _this.workflow(new Workflow(data));
          return _this.configTree(_this.workflow());
        };
      })(this));
    };

    WorkflowBuilderViewModel.prototype.configTree = function(workflow) {
      $("#tree").fancytree({
        extensions: ["dnd"],
        debugLevel: 2,
        source: [workflow],
        imagePath: "images/",
        icons: false,
        dnd: dndOptions,
        click: (function(_this) {
          return function(event, data) {
            return _this.selectedActivity(data.node.data.act);
          };
        })(this)
      });
      return this.tree = $("#tree").fancytree("getTree");
    };

    WorkflowBuilderViewModel.prototype.prettyPrint = function() {
      return new PrettyPrintVisitor(this.tree);
    };

    WorkflowBuilderViewModel.prototype.save = function() {
      var converter, xml;
      converter = new WorkflowXmlConverter(this.tree);
      xml = converter.getXml();
      window.xml = xml;
      console.log(xml);
      return COW.xmlRequest("processes/" + converter.key, "put", xml).done(function() {
        return alert("xml saved");
      });
    };

    return WorkflowBuilderViewModel;

  })();

  WorkflowXmlConverter = (function() {
    function WorkflowXmlConverter(tree) {
      this.addAttributesToNode = __bind(this.addAttributesToNode, this);
      this.createActivityElement = __bind(this.createActivityElement, this);
      this.visitSubprocess = __bind(this.visitSubprocess, this);
      this.visitSignal = __bind(this.visitSignal, this);
      this.visitExit = __bind(this.visitExit, this);
      this.visitScript = __bind(this.visitScript, this);
      this.visitServiceTask = __bind(this.visitServiceTask, this);
      this.visitHumanTask = __bind(this.visitHumanTask, this);
      this.visitLoop = __bind(this.visitLoop, this);
      this.visitOption = __bind(this.visitOption, this);
      this.visitDecision = __bind(this.visitDecision, this);
      this.visitActivities = __bind(this.visitActivities, this);
      this.visitWorkflow = __bind(this.visitWorkflow, this);
      this.visitChildren = __bind(this.visitChildren, this);
      var workflowRoot;
      this.xml = $($.parseXML('<process xmlns="http://www.wiredwidgets.org/cow/server/schema/model-v2"></process>'));
      this.parentXml = this.xml;
      workflowRoot = tree.rootNode.children[0];
      console.log(this.xml);
      this.visit(workflowRoot);
    }

    WorkflowXmlConverter.prototype.getXml = function() {
      return this.xml[0];
    };

    WorkflowXmlConverter.prototype.visit = function(node) {
      return node.data.act.accept(this, node);
    };

    WorkflowXmlConverter.prototype.visitChildren = function(nodeXml, nodeChildren) {
      var child, oldXmlPosition, _i, _len, _ref;
      _ref = [this.parentXml, nodeXml], oldXmlPosition = _ref[0], this.parentXml = _ref[1];
      for (_i = 0, _len = nodeChildren.length; _i < _len; _i++) {
        child = nodeChildren[_i];
        this.visit(child);
      }
      return this.parentXml = oldXmlPosition;
    };

    WorkflowXmlConverter.prototype.visitWorkflow = function(node) {
      var process;
      this.key = node.key;
      process = $(this.parentXml.find("process"));
      this.addAttributesToNode(process, node.data.act.apiAttributes);
      this.createVariablesElement(process, node.data.act.variables);
      return this.visitChildren(process, [node.children[0]]);
    };

    WorkflowXmlConverter.prototype.visitActivities = function(node) {
      var xmlActivities;
      xmlActivities = this.createActivityElement("activities", node);
      return this.visitChildren(xmlActivities, node.children);
    };

    WorkflowXmlConverter.prototype.visitDecision = function(node) {
      var xmlDecision, xmlTask;
      xmlDecision = this.createActivityElement("decision", node);
      xmlTask = this.createTag("task", xmlDecision);
      this.addAttributesToNode(xmlTask, node.data.act.task.apiAttributes);
      return this.visitChildren(xmlDecision, node.children);
    };

    WorkflowXmlConverter.prototype.visitOption = function(node) {
      var xmlOption;
      xmlOption = this.createActivityElement("option", node);
      return this.visitChildren(xmlOption, node.children);
    };

    WorkflowXmlConverter.prototype.visitLoop = function(node) {
      var xmlLoop, xmlLoopTask;
      xmlLoop = this.createActivityElement("loop", node);
      xmlLoopTask = this.createTag("loopTask", xmlLoop);
      this.addAttributesToNode(xmlLoopTask, node.data.act.loopTask.apiAttributes);
      return this.visitChildren(xmlLoop, node.children);
    };

    WorkflowXmlConverter.prototype.visitHumanTask = function(node) {
      return this.createActivityElement("task", node);
    };

    WorkflowXmlConverter.prototype.visitServiceTask = function(node) {
      return this.createActivityElement("serviceTask", node);
    };

    WorkflowXmlConverter.prototype.visitScript = function(node) {
      return this.createActivityElement("script", node);
    };

    WorkflowXmlConverter.prototype.visitExit = function(node) {
      return this.createActivityElement("exit", node);
    };

    WorkflowXmlConverter.prototype.visitSignal = function(node) {
      return this.createActivityElement("signal", node);
    };

    WorkflowXmlConverter.prototype.visitSubprocess = function(node) {
      return this.createActivityElement("subProcess", node);
    };

    WorkflowXmlConverter.prototype.createActivityElement = function(tag, treeNode) {
      var xml;
      xml = this.createTag(tag, this.parentXml);
      this.addAttributesToNode(xml, treeNode.data.act.apiAttributes);
      this.createVariablesElement(xml, treeNode.data.act.variables);
      return xml;
    };

    WorkflowXmlConverter.prototype.createTextElement = function(parent, tag, content) {
      var xml;
      xml = this.createTag(tag, parent);
      xml.text(content);
      return xml;
    };

    WorkflowXmlConverter.prototype.createTag = function(name, parent) {
      var newTag;
      parent.append("<" + name + " class='hack'/>");
      newTag = parent.find(".hack");
      newTag.removeAttr("class");
      return newTag;
    };

    WorkflowXmlConverter.prototype.addAttributesToNode = function(xmlElement, attributes) {
      var attr, unwrappedAttributes, _i, _len, _results;
      unwrappedAttributes = ko.mapping.toJS(attributes);
      _results = [];
      for (_i = 0, _len = unwrappedAttributes.length; _i < _len; _i++) {
        attr = unwrappedAttributes[_i];
        if (attr.value) {
          if (attr.isXmlAttribute) {
            _results.push(xmlElement.attr(attr.key, attr.value));
          } else {
            _results.push(this.createTextElement(xmlElement, attr.key, attr.value));
          }
        }
      }
      return _results;
    };

    WorkflowXmlConverter.prototype.createVariablesElement = function(xmlElement, observableVars) {
      var attrName, attrValue, unwrappedVars, varXml, variable, variablesXml, _i, _len, _results;
      variablesXml = this.createTag("variables", xmlElement);
      unwrappedVars = ko.mapping.toJS(observableVars);
      _results = [];
      for (_i = 0, _len = unwrappedVars.length; _i < _len; _i++) {
        variable = unwrappedVars[_i];
        varXml = this.createTag("variable", variablesXml);
        _results.push((function() {
          var _results1;
          _results1 = [];
          for (attrName in variable) {
            if (!__hasProp.call(variable, attrName)) continue;
            attrValue = variable[attrName];
            _results1.push(varXml.attr(attrName, attrValue));
          }
          return _results1;
        })());
      }
      return _results;
    };

    return WorkflowXmlConverter;

  })();

  Activity = (function() {
    function Activity(data) {
      var _ref, _ref1;
      this.data = data;
      this.readVariables = __bind(this.readVariables, this);
      this.addInvisibleAttr = __bind(this.addInvisibleAttr, this);
      this.addAttr = __bind(this.addAttr, this);
      this.dragEnter = __bind(this.dragEnter, this);
      this.title = (_ref = (_ref1 = this.data) != null ? _ref1.name : void 0) != null ? _ref : this.constructor.name;
      this.icon = "Icon_Task.png";
      this.draggable = true;
      this.expanded = true;
      this.act = this;
      this.isDecision = false;
      this.isActivities = false;
      this.folder = false;
      this.variables = ko.observableArray();
      this.readVariables();
      this.apiAttributes = ko.observableArray();
      this.addAttr("name", "Name", true);
      this.addAttr("description", "Description");
      this.addInvisibleAttr("key", true);
      this.addAttr("bypassable", "Bypassable", true, "checkbox");
    }

    Activity.prototype.dragEnter = function() {
      if (this.folder) {
        return ["over"];
      }
      return ["before", "after"];
    };

    Activity.prototype.addAttr = function(key, label, isXmlAttribute, inputType) {
      var _ref, _ref1;
      if (isXmlAttribute == null) {
        isXmlAttribute = false;
      }
      if (inputType == null) {
        inputType = "text";
      }
      return this.apiAttributes.push({
        key: key,
        value: ko.observable((_ref = (_ref1 = this.data) != null ? _ref1[key] : void 0) != null ? _ref : ""),
        label: label,
        isXmlAttribute: isXmlAttribute,
        inputType: inputType
      });
    };

    Activity.prototype.addInvisibleAttr = function(key, isXmlAttribute) {
      if (isXmlAttribute == null) {
        isXmlAttribute = false;
      }
      return this.addAttr(key, null, isXmlAttribute);
    };

    Activity.prototype.readVariables = function() {
      var v, varList, _i, _len, _ref, _ref1, _results;
      varList = (_ref = this.data) != null ? (_ref1 = _ref.variables) != null ? _ref1.variable : void 0 : void 0;
      if (varList == null) {
        return;
      }
      _results = [];
      for (_i = 0, _len = varList.length; _i < _len; _i++) {
        v = varList[_i];
        _results.push(this.variables.push(this.createObservableVar(v)));
      }
      return _results;
    };

    Activity.prototype.createObservableVar = function(variable) {
      var _ref, _ref1;
      return {
        name: ko.observable(variable.name),
        value: ko.observable(variable.value),
        type: ko.observable(variable.type),
        required: ko.observable((_ref = variable.required) != null ? _ref : false),
        output: ko.observable((_ref1 = variable.output) != null ? _ref1 : false)
      };
    };

    return Activity;

  })();

  Workflow = (function(_super) {
    __extends(Workflow, _super);

    function Workflow(data) {
      this.data = data;
      this.key = this.data.key;
      this.title = "<span class='glyphicon glyphicon-list-alt'></span> " + this.key;
      this.children = [ActivityFactory.create(this.data.activity)];
      this.draggable = false;
      this.folder = true;
      this.expanded = true;
      this.act = this;
      this.variables = ko.observableArray();
      this.readVariables();
      this.apiAttributes = ko.observableArray();
      this.addAttr("name", "Name", true);
      this.addAttr("bypassAssignee", "Bypass Assignee");
      this.addAttr("bypassCandidateUsers", "Bypass Candidate Users");
      this.addAttr("bypassCandidateGroups", "Bypass Candidate Groups");
      this.addInvisibleAttr("key", true);
    }

    Workflow.prototype.dragEnter = function() {
      return false;
    };

    Workflow.prototype.accept = function(visitor, node) {
      return visitor.visitWorkflow(node);
    };

    return Workflow;

  })(Activity);

  Activities = (function(_super) {
    __extends(Activities, _super);

    Activities.typeString = "org.wiredwidgets.cow.server.api.model.v2.Activities";

    function Activities(data) {
      this.dragEnter = __bind(this.dragEnter, this);
      var childActivitiesData, d, _ref, _ref1, _ref2, _ref3;
      Activities.__super__.constructor.call(this, data);
      this.isSequential = (_ref = (_ref1 = this.data) != null ? _ref1.sequential : void 0) != null ? _ref : true;
      if (((_ref2 = this.data) != null ? _ref2.name : void 0) != null) {
        this.title = this.data.name;
      } else {
        this.title = this.isSequential ? "List" : "Parallel List";
      }
      childActivitiesData = (_ref3 = this.data) != null ? _ref3.activity : void 0;
      if (childActivitiesData) {
        this.children = (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = childActivitiesData.length; _i < _len; _i++) {
            d = childActivitiesData[_i];
            _results.push(ActivityFactory.create(d));
          }
          return _results;
        })();
      } else {
        this.children = [];
      }
      this.icon = "Icon_List.png";
      this.folder = true;
      this.isActivities = true;
      this.addAttr("sequential", "Is Sequential", true, "checkbox");
      this.addAttr("mergeCondition", "Merge Condition", true);
    }

    Activities.prototype.dragEnter = function(data) {
      var acitivity, _ref;
      acitivity = (_ref = data.node.getParent()) != null ? _ref.data.act : void 0;
      if ((acitivity != null ? acitivity.isDecision : void 0) && data.otherNode.data.act.isActivities) {
        return ["over", "after", "before"];
      } else {
        return ["over"];
      }
    };

    Activities.prototype.accept = function(visitor, node) {
      return visitor.visitActivities(node);
    };

    Activities.prototype.typeStr = function() {
      return Activities.typeString;
    };

    return Activities;

  })(Activity);

  HumanTask = (function(_super) {
    __extends(HumanTask, _super);

    HumanTask.typeString = "org.wiredwidgets.cow.server.api.model.v2.Task";

    function HumanTask(data) {
      this.data = data;
      HumanTask.__super__.constructor.call(this, this.data);
      if (this.data != null) {
        this.assignee = data.assignee;
        this.candidateGroups = data.candidateGroups;
      }
      this.addAttr("assignee", "Assignee");
      this.addAttr("candidateUsers", "Candidate users");
      this.addAttr("candidateGroups", "Candidate groups");
      this.addAttr("createTime", "Create time");
      this.addAttr("endTime", "End time");
    }

    HumanTask.prototype.accept = function(visitor, node) {
      return visitor.visitHumanTask(node);
    };

    HumanTask.prototype.typeStr = function() {
      return HumanTask.typeString;
    };

    return HumanTask;

  })(Activity);

  ServiceTask = (function(_super) {
    __extends(ServiceTask, _super);

    ServiceTask.typeString = "org.wiredwidgets.cow.server.api.model.v2.ServiceTask";

    function ServiceTask(data) {
      this.data = data;
      ServiceTask.__super__.constructor.call(this, this.data);
      this.icon = "Icon_ServiceTask.png";
      this.addAttr("url", "URL");
      this.addAttr("content", "Content");
      this.addAttr("contentType", "Content type");
      this.addAttr("var", "Result variable");
    }

    ServiceTask.prototype.accept = function(visitor, node) {
      return visitor.visitServiceTask(node);
    };

    ServiceTask.prototype.typeStr = function() {
      return ServiceTask.typeString;
    };

    return ServiceTask;

  })(Activity);

  ScriptTask = (function(_super) {
    __extends(ScriptTask, _super);

    ScriptTask.typeString = "org.wiredwidgets.cow.server.api.model.v2.Script";

    function ScriptTask(data) {
      ScriptTask.__super__.constructor.call(this, data);
      this.icon = "Icon_Script.png";
      this.addAttr("import", "Imports");
      this.addAttr("content", "Content");
    }

    ScriptTask.prototype.accept = function(visitor, node) {
      return visitor.visitScript(node);
    };

    ScriptTask.prototype.typeStr = function() {
      return ScriptTask.typeString;
    };

    return ScriptTask;

  })(Activity);

  Decision = (function(_super) {
    __extends(Decision, _super);

    Decision.typeString = "org.wiredwidgets.cow.server.api.model.v2.Decision";

    function Decision(data) {
      this.dragEnter = __bind(this.dragEnter, this);
      var opt, optionsData;
      Decision.__super__.constructor.call(this, data);
      optionsData = data != null ? data.option : void 0;
      if (optionsData) {
        this.children = (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = optionsData.length; _i < _len; _i++) {
            opt = optionsData[_i];
            _results.push(new Option(opt));
          }
          return _results;
        })();
      } else {
        this.children = [];
      }
      this.icon = "Icon_Decision.png";
      this.folder = true;
      this.isDecision = true;
      this.task = new HumanTask(data != null ? data.task : void 0);
    }

    Decision.prototype.dragEnter = function(data) {
      if (data.otherNode.data.act.isActivities) {
        return ["over"];
      } else {
        return false;
      }
    };

    Decision.prototype.accept = function(visitor, node) {
      return visitor.visitDecision(node);
    };

    Decision.prototype.typeStr = function() {
      return Decision.typeString;
    };

    return Decision;

  })(Activity);

  Option = (function(_super) {
    __extends(Option, _super);

    function Option(data) {
      var childActivitiesData, _ref;
      this.data = data;
      Option.__super__.constructor.call(this, this.data);
      this.icon = "Icon_Decision_Arrow.png";
      childActivitiesData = (_ref = this.data) != null ? _ref.activity : void 0;
      if (childActivitiesData) {
        this.children = [ActivityFactory.create(childActivitiesData)];
      } else {
        this.children = [];
      }
      this.folder = true;
    }

    Option.prototype.accept = function(visitor, node) {
      return visitor.visitOption(node);
    };

    return Option;

  })(Activity);

  Exit = (function(_super) {
    __extends(Exit, _super);

    Exit.typeString = "org.wiredwidgets.cow.server.api.model.v2.Exit";

    function Exit(data) {
      Exit.__super__.constructor.call(this, data);
      this.icon = "Icon_Exit.png";
      this.addAttr("state", "State", true);
    }

    Exit.prototype.accept = function(visitor, node) {
      return visitor.visitExit(node);
    };

    Exit.prototype.typeStr = function() {
      return Exit.typeString;
    };

    return Exit;

  })(Activity);

  Signal = (function(_super) {
    __extends(Signal, _super);

    Signal.typeString = "org.wiredwidgets.cow.server.api.model.v2.Signal";

    function Signal(data) {
      Signal.__super__.constructor.call(this, data);
      this.icon = "Icon_Signal.png";
      this.addAttr("signalId", "Signal Id", true);
    }

    Signal.prototype.accept = function(visitor, node) {
      return visitor.visitSignal(node);
    };

    Signal.prototype.typeStr = function() {
      return Signal.typeString;
    };

    return Signal;

  })(Activity);

  Subprocess = (function(_super) {
    __extends(Subprocess, _super);

    Subprocess.typeString = "org.wiredwidgets.cow.server.api.model.v2.SubProcess";

    function Subprocess(data) {
      Subprocess.__super__.constructor.call(this, data);
      this.icon = "Icon_SubProcess.png";
    }

    Subprocess.prototype.accept = function(visitor, node) {
      return visitor.visitSubprocess(node);
    };

    Subprocess.prototype.typeStr = function() {
      return Subprocess.typeString;
    };

    return Subprocess;

  })(Activity);

  Loop = (function(_super) {
    __extends(Loop, _super);

    Loop.typeString = "org.wiredwidgets.cow.server.api.model.v2.Loop";

    function Loop(data) {
      var childData, _ref;
      Loop.__super__.constructor.call(this, data);
      childData = (_ref = this.data) != null ? _ref.activity : void 0;
      if (childData) {
        this.children = [ActivityFactory.create(childData)];
      } else {
        this.children = [];
      }
      this.loopTask = new HumanTask(data != null ? data.loopTask : void 0);
      this.icon = "Icon_Loop.png";
      this.folder = true;
      this.addAttr("doneName", "Done name", true);
      this.addAttr("repeatName", "Repeat name", true);
      this.addAttr("executionCount", "Execution count", true);
    }

    Loop.prototype.accept = function(visitor, node) {
      return visitor.visitLoop(node);
    };

    Loop.prototype.typeStr = function() {
      return Loop.typeString;
    };

    return Loop;

  })(Activity);

  ActivityFactory = (function() {
    function ActivityFactory() {}

    ActivityFactory.typeMap = {};

    ActivityFactory.typeMap[Activities.typeString] = Activities;

    ActivityFactory.typeMap[HumanTask.typeString] = HumanTask;

    ActivityFactory.typeMap[ServiceTask.typeString] = ServiceTask;

    ActivityFactory.typeMap[ScriptTask.typeString] = ScriptTask;

    ActivityFactory.typeMap[Decision.typeString] = Decision;

    ActivityFactory.typeMap[Exit.typeString] = Exit;

    ActivityFactory.typeMap[Loop.typeString] = Loop;

    ActivityFactory.typeMap[Signal.typeString] = Signal;

    ActivityFactory.create = function(data) {
      return new this.typeMap[data.declaredType](data.value);
    };

    ActivityFactory.all = function() {
      var act, key, _ref, _results;
      _ref = this.typeMap;
      _results = [];
      for (key in _ref) {
        act = _ref[key];
        _results.push(new act());
      }
      return _results;
    };

    return ActivityFactory;

  })();

  PrettyPrintVisitor = (function() {
    function PrettyPrintVisitor(tree) {
      var workflowRoot;
      this.tree = tree;
      this.dedent = __bind(this.dedent, this);
      this.indent = __bind(this.indent, this);
      this.tabs = "";
      workflowRoot = this.tree.rootNode.children[0];
      this.visit(workflowRoot);
    }

    PrettyPrintVisitor.prototype.display = function(title) {
      return console.log(this.tabs + title);
    };

    PrettyPrintVisitor.prototype.indent = function() {
      return this.tabs += "\t";
    };

    PrettyPrintVisitor.prototype.dedent = function() {
      return this.tabs = this.tabs.substr(1);
    };

    PrettyPrintVisitor.prototype.visit = function(node) {
      return node.data.act.accept(this, node);
    };

    PrettyPrintVisitor.prototype.visitChildren = function(node) {
      var child, _i, _len, _ref;
      this.indent();
      _ref = node.children;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        child = _ref[_i];
        this.visit(child);
      }
      return this.dedent();
    };

    PrettyPrintVisitor.prototype.visitWorkflow = function(node) {
      this.display(node.key);
      return this.visitChildren(node);
    };

    PrettyPrintVisitor.prototype.visitActivities = function(node) {
      this.display(node.title);
      return this.visitChildren(node);
    };

    PrettyPrintVisitor.prototype.visitHumanTask = function(node) {
      return this.display(node.title);
    };

    PrettyPrintVisitor.prototype.visitServiceTask = function(node) {
      return this.display(node.title);
    };

    PrettyPrintVisitor.prototype.visitScript = function(node) {
      return this.display(node.title);
    };

    PrettyPrintVisitor.prototype.visitDecision = function(node) {
      this.display(node.title);
      return this.visitChildren(node);
    };

    PrettyPrintVisitor.prototype.visitOption = function(node) {
      this.display(node.title);
      return this.visitChildren(node);
    };

    PrettyPrintVisitor.prototype.visitExit = function(node) {
      return this.display(node.title);
    };

    PrettyPrintVisitor.prototype.visitLoop = function(node) {
      this.display(node.title);
      return this.visitChildren(node);
    };

    PrettyPrintVisitor.prototype.visitSignal = function(node) {
      return this.display(node.title);
    };

    PrettyPrintVisitor.prototype.visitSubprocess = function(node) {
      return this.display(node.title);
    };

    return PrettyPrintVisitor;

  })();

}).call(this);

//# sourceMappingURL=workflowbuilder.map
