package org.wiredwidgets.cow.ac.client.ui;

import java.awt.BorderLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.util.ImageUtilities;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import org.wiredwidgets.cow.ac.client.controllers.TaskController;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//org.wiredwidgets.cow.ac.client.ui//Cow//EN",
autostore = false)
public final class CowTopComponent extends TopComponent {

    private static CowTopComponent instance;
    /** path to the icon used by the component and its open action */
    static final String ICON_PATH = "org/wiredwidgets/cow/ac/client/images/cowicon16x16.png";
    private static final String PREFERRED_ID = "CowTopComponent";

    /**
     * A globally accessible messaging location. The StatusBar object itself is a
     * singleton, allowing other components to access it through the class rather than
     * having to reference it via this TopComponent.
     */
    private StatusBar statusBar;
    
    public CowTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(CowTopComponent.class, "CTL_CowTopComponent"));
        setToolTipText(NbBundle.getMessage(CowTopComponent.class, "HINT_CowTopComponent"));
        setIcon(ImageUtilities.loadImage(ICON_PATH, true));

        // the status bar couldn't be added via gui designer because of the
        // getInstance constructor -- which probably means there's a more correct
        // way to do it, but this seems to work well enough
        statusBar = StatusBar.getInstance();
        add(statusBar, BorderLayout.SOUTH);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tasksPanel1 = new org.wiredwidgets.cow.ac.client.ui.TasksPanel();

        setMinimumSize(new java.awt.Dimension(400, 50));
        setLayout(new java.awt.BorderLayout());

        tasksPanel1.setMinimumSize(new java.awt.Dimension(300, 200));
        tasksPanel1.setPreferredSize(new java.awt.Dimension(500, 250));
        add(tasksPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.wiredwidgets.cow.ac.client.ui.TasksPanel tasksPanel1;
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link #findInstance}.
     */
    public static synchronized CowTopComponent getDefault() {
        if (instance == null) {
            instance = new CowTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the CowTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized CowTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(CowTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof CowTopComponent) {
            return (CowTopComponent) win;
        }
        Logger.getLogger(CowTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID
                + "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    @Override
    public void componentOpened() {
        // make a best effort to with populated data
        TaskController.getInstance().refreshTasks();
    }

    @Override
    public void componentClosed() {
        // add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // store your settings
    }

    Object readProperties(java.util.Properties p) {
        if (instance == null) {
            instance = this;
        }
        instance.readPropertiesImpl(p);
        return instance;
    }

    private void readPropertiesImpl(java.util.Properties p) {
        String version = p.getProperty("version");
        // read your settings according to their version
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }
}
