package org.wiredwidgets.cow.ac.util;

import java.awt.Color;
import java.awt.Graphics;

/**
 * A simple little panel to provide some better graphical separation
 * Based on "Hack #36" from the book, "Swing Hacks" by Mariacci and Adamson
 * @author RYANMILLER
 */
public class SeparatorPanel extends javax.swing.JPanel {

    private Color leftColor;
    private Color rightColor;

    /** Creates new form SeparatorPanel */
    public SeparatorPanel() {
        initComponents();
        leftColor = Color.GRAY;
        rightColor = Color.WHITE;
        setOpaque(false);
    }

    /**
     * Sets the colors on either side of the separator.
     * @param left Color for the left pane
     * @param right Color for the right pane
     */
    public SeparatorPanel(Color left, Color right) {
        initComponents();
        this.leftColor = left;
        this.rightColor = right;
        setOpaque(false);
    }

    @Override
    protected void paintComponent(Graphics g) {
        g.setColor(leftColor);
        g.drawLine(0, 0, 0, getHeight());
        g.setColor(rightColor);
        g.drawLine(1, 0, 1, getHeight());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
